"""Environment variable names used across services (for docs and validation)."""

OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_MODEL = "OPENAI_MODEL"
OPENAI_BASE_URL = "OPENAI_BASE_URL"

CONVERSATION_SERVICE_URL = "CONVERSATION_SERVICE_URL"
ASSESSMENT_SERVICE_URL = "ASSESSMENT_SERVICE_URL"
FRAMEWORK_SERVICE_URL = "FRAMEWORK_SERVICE_URL"
LLM_CONVERSATION_SERVICE_URL = "LLM_CONVERSATION_SERVICE_URL"
EVALUATION_SERVICE_DIR = "EVALUATION_SERVICE_DIR"
VITE_API_URL = "VITE_API_URL"
